source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'rb-readline', '~> 0.4.2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'dotenv-rails'

#gem 'sqlite3'
group :development, :test do
  gem 'sqlite3'
end

group :staging, :production do
  gem 'mysql2'
end

#removes white spaces at the start and end of attribute strings
gem "strip_attributes", "~> 1.2"

# Needed to make execjs work. upgrade to ruby 2.0 first.
gem 'libv8'
gem 'therubyracer'

#write json data back to ajax request
gem 'jbuilder'

# allow i18n stuff in rails to be used by JS
gem 'i18n-js'

# moving around pages using ajax
gem 'wiselinks'

#authentication
#gem 'sorcery'
#gem 'omniauth-google-oauth2'

# add ancestry
#gem 'closure_tree'

#for static pages
gem 'high_voltage'
#
#
# Gems used only for assets and not required
# in production environments by default

gem 'sass-rails'
gem 'coffee-rails'
gem 'compass-rails', '>= 2.0.alpha.0'
gem 'jquery-rails'
gem 'oily_png'
gem 'sassy-buttons'
gem 'salsa'
gem 'modernizr-rails'
gem 'uglifier', '>= 1.0.3'


group :test do
  gem 'cucumber-rails', require: false
  gem 'capybara'
  gem 'capybara-firebug'
  gem 'launchy'
  # bug in 1.1.1 and sqlite3 #issue 224
  gem 'database_cleaner', "< 1.1.0"
  gem 'rspec-rails', '>= 2.6.1'
  gem 'selenium-webdriver'
  gem 'poltergeist'
end

group :test, :development do
  gem 'guard-rails'
  gem 'guard-bundler'
  gem 'guard-rspec'
  gem 'guard-livereload'
  gem 'guard-cucumber'
  gem 'factory_girl_rails'
  gem 'pry'
  gem 'pry-doc'
  gem 'shoulda-matchers'
  gem 'libnotify'
  gem 'rb-inotify', '~> 0.9'
  gem 'delorean'
  gem 'better_errors'
  gem 'binding_of_caller'
end

gem 'squeel', '>= 0.8.10'

# view/HTML management
gem 'haml-rails'

# Form management
gem 'simple_form'

# Deploy with Capistrano
gem 'capistrano'
gem 'capistrano-ext'
gem 'rvm-capistrano'

# Web Server
gem 'thin'



